@host = http://localhost:5277

GET {{host}}/
Accept: application/json

###

GET {{host}}/health

###

GET {{host}}/api/v1/customers
Accept: application/json

###

POST {{host}}/api/v1/customers
Content-Type: application/json

{
  "firstName": "Grace",
  "lastName": "Hopper",
  "email": "grace@example.com"
}
